name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl --location --request GET 'https://gateway.apiportal.ns.nl/reisinformatie-api/api/v3/disruptions' \
        --header 'Ocp-Apim-Subscription-Key: ${{ secrets.NS_API_KEY }}' > storingen.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
